[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static", # Use static relocation model for bare-metal
    "-C", "code-model=small", # Disable position-independent executables
    "-C", "prefer-dynamic=no", # Prefer static linking
    "-C", "force-frame-pointers=yes",
]
